In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Ronal\OneDrive\Desktop\pandas-sales-analysis\data\sales.csv")

In [13]:
df.groupby("region")["order_id"].count().sort_values(ascending=False)

region
East     5
North    5
South    5
West     5
Name: order_id, dtype: int64

In [9]:
df["total"] = df["quantity"] * df["price"]

df.groupby("product")["total"].sum().sort_values(ascending=False)

product
Laptop        4250
Phone         4200
Monitor       1800
Tablet        1600
Headphones     800
Keyboard       765
Mouse          550
Name: total, dtype: int64

In [8]:
df["total"] = df["quantity"] * df["price"]

df.groupby("category")["total"].sum().sort_values(ascending=False)

category
Electronics    11850
Accessories     2115
Name: total, dtype: int64

In [3]:
df[df["price"] > 100 ].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max      mean
region
East      1    3  2.000000
North     1    3  2.000000
South     1    2  1.333333
West      2    2  2.000000

In [2]:
df[df["quantity"] > 3].groupby("category")["price"].agg(["min", "max", "mean"])

             min  max   mean
category
Accessories   25   80  46.25

In [10]:
df[df["price"] < 100 ].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max   mean
category
Accessories    4   10  6.125

In [9]:
df[df["quantity"] > 1].groupby("region")["price"].agg(["min", "max", "mean"])

        min  max    mean
region
East     45  400  206.25
North    25  850  443.75
South    25  600  235.00
West     25  600  223.00

In [8]:
df[df["price"] > 200 ].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max      mean
category
Electronics    1    3  1.833333

In [7]:
df[df["quantity"] < 4 ].groupby("region") ["price"].agg(["min", "max", "mean"])

        min  max        mean
region
East    300  850  516.666667
North   300  850  650.000000
South   300  850  583.333333
West    400  600  500.000000

In [6]:
df[df["price"] > 50].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max      mean
category
Accessories    4    6  5.000000
Electronics    1    3  1.833333

In [5]:
df[df["quantity"] > 3].groupby("category")["price"].agg(["min", "max", "mean"])

             min  max   mean
category
Accessories   25   80  46.25

In [4]:
df[df["price"] < 200 ].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max       mean
region
East      5    6   5.500000
North    10   10  10.000000
South     4    5   4.500000
West      4    8   6.333333

In [3]:
df[df["quantity"] > 2].groupby("category")["price"].agg(["min", "max", "mean"])

             min  max    mean
category
Accessories   25   80   46.25
Electronics  300  600  450.00

In [2]:
df[df["price"] > 100 ].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max      mean
region
East      1    3  2.000000
North     1    3  2.000000
South     1    2  1.333333
West      2    2  2.000000

In [ ]:


df[df["price"] > 300 ].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max      mean
category
Electronics    1    3  1.777778

In [9]:
df[df["price"] > 300 ].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max      mean
category
Electronics    1    3  1.777778

In [8]:
df[df["quantity"] > 2].groupby("region")["price"].agg(["min", "max", "mean"])

        min  max        mean
region
East     45  300  141.666667
North    25  600  312.500000
South    25   80   52.500000
West     25   45   38.333333

In [7]:
df[df["price"] < 300 ].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max       mean
region
East      5    6   5.500000
North    10   10  10.000000
South     4    5   4.500000
West      4    8   6.333333

In [ ]:
df[df["quantity"] > 1].groupby("category")["price"].agg(["min", "max", "mean"])

In [6]:
df[df["price"] > 50 ].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max  mean
region
East      1    6   3.0
North     1    3   2.0
South     1    4   2.0
West      2    2   2.0

In [5]:
df[df["quantity"] < 4 ].groupby("region")["price"].agg(["min", "max", "mean"])

        min  max        mean
region
East    300  850  516.666667
North   300  850  650.000000
South   300  850  583.333333
West    400  600  500.000000

In [4]:

df[df["price"] > 100].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max      mean
category
Electronics    1    3  1.833333

In [3]:
df[df["quantity"] > 3].groupby("region")["price"].agg(["min", "max", "mean"])

        min  max       mean
region
East     45   80  62.500000
North    25   25  25.000000
South    25   80  52.500000
West     25   45  38.333333

In [2]:

df[df["price"] < 500].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max      mean
region
East      2    6  4.000000
North     2   10  6.000000
South     1    5  3.333333
West      2    8  5.250000

In [13]:
df[df["quantity"] > 1].groupby("category")["price"].agg(["min", "max", "mean"])

             min  max    mean
category
Accessories   25   80   46.25
Electronics  300  850  506.25

In [12]:
df[df["price"] > 200].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max      mean
region
East      1    3  2.000000
North     1    3  2.000000
South     1    2  1.333333
West      2    2  2.000000

In [11]:
df[df["quantity"] > 2].groupby("category")["price"].agg(["min", "max", "mean"])

             min  max    mean
category
Accessories   25   80   46.25
Electronics  300  600  450.00

In [10]:
df[df["price"] < 100 ].groupby("region")["quantity"].agg(["min", "max", "mean"])

        min  max       mean
region
East      5    6   5.500000
North    10   10  10.000000
South     4    5   4.500000
West      4    8   6.333333

In [9]:
df[df["quantity"] > 3].groupby("category")["price"].agg(["min", "max", "mean"])

             min  max   mean
category
Accessories   25   80  46.25

In [8]:
df[df["price"] > 50].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max      mean
category
Accessories    4    6  5.000000
Electronics    1    3  1.833333

In [7]:
df[df["quantity"] > 2 ].groupby("region")["price"].agg(["min", "max", "mean"])

        min  max        mean
region
East     45  300  141.666667
North    25  600  312.500000
South    25   80   52.500000
West     25   45   38.333333

In [6]:
df[df["price"] > 100].groupby("category")["quantity"].agg(["min", "max", "mean"])

             min  max      mean
category
Electronics    1    3  1.833333

In [ ]:

df[df["quantity"] > 3].groupby("region")["price"].agg(["min", "max", "mean"])

        min  max       mean
region
East     45   80  62.500000
North    25   25  25.000000
South    25   80  52.500000
West     25   45  38.333333

In [3]:
df[df["price"] > 100].groupby("category")["quantity"].sum().sort_values(ascending=False)

category
Electronics    22
Name: quantity, dtype: int64

In [2]:
df[df["quantity"] > 2].groupby("category")["price"].agg(["min", "max"])

             min  max
category
Accessories   25   80
Electronics  300  600

In [14]:
df[df["price"] > 50].groupby("region")["quantity"].mean()

region
East     3.0
North    2.0
South    2.0
West     2.0
Name: quantity, dtype: float64

In [13]:
df[df["quantity"] > 2].groupby("category")["price"].sum().sort_values(ascending=False)

category
Electronics    900
Accessories    370
Name: price, dtype: int64

In [9]:
df.groupby(["category"])["price"].mean().sort_values(ascending=False)

category
Electronics    575.00
Accessories     46.25
Name: price, dtype: float64

In [6]:
df.groupby(["category", "region"])["quantity"].agg(["sum", "mean"])

                    sum       mean
category    region
Accessories East     11   5.500000
            North    10  10.000000
            South     9   4.500000
            West     19   6.333333
Electronics East      6   2.000000
            North     8   2.000000
            South     4   1.333333
            West      4   2.000000

In [4]:
df.groupby(["category", "region"])["price"].mean()

category     region
Accessories  East       62.500000
             North      25.000000
             South      52.500000
             West       38.333333
Electronics  East      516.666667
             North     650.000000
             South     583.333333
             West      500.000000
Name: price, dtype: float64

In [3]:
df.groupby(["category", "region"])["quantity"].sum()

category     region
Accessories  East      11
             North     10
             South      9
             West      19
Electronics  East       6
             North      8
             South      4
             West       4
Name: quantity, dtype: int64

In [2]:
df.groupby("category").agg({"quantity": "sum", "price": "mean"})

             quantity   price
category
Accessories        49   46.25
Electronics        22  575.00

In [19]:
df.groupby("category")["price"].agg(["min", "max", "mean"])

             min  max    mean
category
Accessories   25   80   46.25
Electronics  300  850  575.00

In [18]:
df["price"].agg(["min", "max", "mean"])

min      25.0
max     850.0
mean    363.5
Name: price, dtype: float64

In [17]:
df["price"].median()

np.float64(300.0)

In [13]:
df["price"].mean()

np.float64(363.5)

In [16]:
df["quantity"].std()

np.float64(2.564432839727663)

In [15]:
df["customer"].count()

np.int64(20)

In [12]:
df["price"].sum()

np.int64(7270)

In [11]:
df["price"].min()

np.int64(25)

In [10]:
df["price"].max()

np.int64(850)

In [3]:
df.groupby("region")["quantity"].sum().sort_values(ascending=False)

region
West     23
North    18
East     17
South    13
Name: quantity, dtype: int64

In [2]:
df[df["price"] > 50].groupby("region")["quantity"].sum()

region
East     12
North     8
South     8
West      4
Name: quantity, dtype: int64

In [10]:
df[df["price"] > 100].groupby("region")["quantity"].sum().sort_values(ascending=False)

region
North    8
East     6
South    4
West     4
Name: quantity, dtype: int64

In [6]:
df.groupby("region")["price"].mean().sort_values(ascending=True)

region
North    525.0
South    371.0
East     335.0
West     223.0
Name: price, dtype: float64

In [3]:
df.groupby("category")["price"].agg(["min", "max"])

             min  max
category
Accessories   25   80
Electronics  300  850

In [11]:
df["total"] = df["quantity"] * df["price"]
df.groupby("region")["total"].sum()

region
East     3255
North    5200
South    2795
West     2715
Name: total, dtype: int64

In [7]:
df.groupby("category")["quantity"].mean()

category
Accessories    6.125000
Electronics    1.833333
Name: quantity, dtype: float64

In [6]:
df[df["category"] == "Electronics"]["price"].sum()

np.int64(6900)

In [6]:
df.pivot_table( values="price",
index="category",
aggfunc="mean"

)

              price
category
Accessories   46.25
Electronics  575.00

In [4]:
df["quantity"].apply(lambda x: x * 2)

0      4
1     10
2      6
3      8
4      2
5      4
6     12
7      4
8     20
9      2
10     2
11    16
12     6
13     8
14     4
15    14
16     4
17     2
18    10
19     4
Name: quantity, dtype: int64

In [3]:
df.query("quantity > 3")

,order_id,date,customer,product,category,quantity,price,region
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West
6,1007,2026-01-18,John,Headphones,Accessories,6,80,East
8,1009,2026-01-22,Carlos,Mouse,Accessories,10,25,North
11,1012,2026-02-05,Maria,Keyboard,Accessories,8,45,West
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South
15,1016,2026-02-18,Maria,Mouse,Accessories,7,25,West
18,1019,2026-02-25,John,Keyboard,Accessories,5,45,East

In [4]:
df.iloc[[5]][["product", "price"]]

  product  price
5   Phone    600

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    20 non-null     int64
 1   date        20 non-null     str
 2   customer    20 non-null     str
 3   product     20 non-null     str
 4   category    20 non-null     str
 5   quantity    20 non-null     int64
 6   price       20 non-null     int64
 7   region      20 non-null     str
 8   total       20 non-null     int64
 9   high_price  20 non-null     bool
dtypes: bool(1), int64(4), str(5)
memory usage: 1.6 KB

In [4]:
df['product'].unique()

<StringArray>
['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Phone', 'Headphones', 'Tablet']
Length: 7, dtype: str

In [11]:

pd.merge(df1, df2, on="customer")

NameError: name 'df1' is not defined

In [7]:
df["date"].dt.day_name()

0        Monday
1       Tuesday
2      Thursday
3      Saturday
4        Monday
5      Thursday
6        Sunday
7       Tuesday
8      Thursday
9        Sunday
10       Monday
11     Thursday
12       Sunday
13     Thursday
14       Sunday
15    Wednesday
16       Friday
17       Sunday
18    Wednesday
19     Saturday
Name: date, dtype: str

In [13]:
df["customer"].nunique()

4

In [14]:
df["product"].value_counts()

product
Laptop        4
Mouse         3
Monitor       3
Keyboard      3
Phone         3
Headphones    2
Tablet        2
Name: count, dtype: int64

In [16]:
df.groupby("region")["quantity"].sum()

region
East     17
North    18
South    13
West     23
Name: quantity, dtype: int64

In [6]:

df["date"].dt.day

0      5
1      6
2      8
3     10
4     12
5     15
6     18
7     20
8     22
9     25
10     2
11     5
12     8
13    12
14    15
15    18
16    20
17    22
18    25
19    28
Name: date, dtype: int32

In [23]:
df["customer"].isna().sum()

np.int64(0)

In [12]:
df.groupby("category")["quantity"].sum().sort_values(ascending=False)

category
Accessories    49
Electronics    22
Name: quantity, dtype: int64

In [14]:
df["total"] = df["quantity"] * df["price"]

In [22]:
df["customer"].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: customer, dtype: bool

In [21]:
df.rename(columns={"costomer": "costomer_name"})

,order_id,date,customer,product,category,quantity,price,region,total,high_price
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North,1700,True
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South,125,True
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East,900,True
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West,180,True
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North,850,True
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South,1200,True
6,1007,2026-01-18,John,Headphones,Accessories,6,80,East,480,True
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West,800,True
8,1009,2026-01-22,Carlos,Mouse,Accessories,10,25,North,250,True
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South,300,True
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East,850,True
11,1012,2026-02-05,Maria,Keyboard,Accessories,8,45,West,360,True
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North,1800,True
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South,320,True
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East,800,True
15,1016,2026-02-18,Maria,Mouse,Accessories,7,25,West,175,True
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North,600,True
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South,850,True
18,1019,2026-02-25,John,Keyboard,Accessories,5,45,East,225,True
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West,1200,True

In [ ]:
df["high_price"] = df["price"] > 300

In [17]:
df.groupby("category")["price"].mean()

category
Accessories     46.25
Electronics    575.00
Name: price, dtype: float64

In [24]:
df.groupby("region")["order_id"].count()

region
East     5
North    5
South    5
West     5
Name: order_id, dtype: int64

In [16]:
df["quantity"].sum()

np.int64(71)

In [6]:
df.groupby("region")["quantity"].agg(["sum", "mean"])

        sum  mean
region
East     17   3.4
North    18   3.6
South    13   2.6
West     23   4.6

In [6]:
df[df["category"] == "Electronics"].groupby("region")["quantity"].sum()

region
East     6
North    8
South    4
West     4
Name: quantity, dtype: int64

In [2]:
df.sort_values("quantity", ascending=False)

,order_id,date,customer,product,category,quantity,price,region
8,1009,2026-01-22,Carlos,Mouse,Accessories,10,25,North
11,1012,2026-02-05,Maria,Keyboard,Accessories,8,45,West
15,1016,2026-02-18,Maria,Mouse,Accessories,7,25,West
6,1007,2026-01-18,John,Headphones,Accessories,6,80,East
18,1019,2026-02-25,John,Keyboard,Accessories,5,45,East
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South

In [7]:
df.loc[0,["customer", "region"]]

customer    Carlos
region       North
Name: 0, dtype: str

In [8]:
df.loc[5,["product", "price"]]

product    Phone
price        600
Name: 5, dtype: object

In [10]:
df[(df["price"] < 80) & (df["region"] == "South")]

   order_id        date customer product     category  quantity  price region
1      1002  2026-01-06      Ana   Mouse  Accessories         5     25  South

In [19]:
df[(df["category"] == "Electronics") | (df["category"] == "Furniture")]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West

In [13]:
df[df["quantity"].between(2, 5)]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
18,1019,2026-02-25,John,Keyboard,Accessories,5,45,East
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West

In [11]:
df[df["category"].isin(["Electronics", "Furniture"])]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West

In [8]:
df[df["category"] != "North"]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
6,1007,2026-01-18,John,Headphones,Accessories,6,80,East
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
8,1009,2026-01-22,Carlos,Mouse,Accessories,10,25,North
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East
11,1012,2026-02-05,Maria,Keyboard,Accessories,8,45,West
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
15,1016,2026-02-18,Maria,Mouse,Accessories,7,25,West
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South
18,1019,2026-02-25,John,Keyboard,Accessories,5,45,East
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West

In [6]:
df[df["region"] == "South"]

,order_id,date,customer,product,category,quantity,price,region
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South

In [3]:
df[df["price"] < 30]

    order_id        date customer product     category  quantity  price region
1       1002  2026-01-06      Ana   Mouse  Accessories         5     25  South
8       1009  2026-01-22   Carlos   Mouse  Accessories        10     25  North
15      1016  2026-02-18    Maria   Mouse  Accessories         7     25   West

In [7]:
row, column = df.shape
print('row:', row)
print('column:', column)

row: 20
column: 8

In [19]:
df.dtypes

order_id    int64
date          str
customer      str
product       str
category      str
quantity    int64
price       int64
region        str
dtype: object

In [15]:
list(df.columns)

['order_id',
 'date',
 'customer',
 'product',
 'category',
 'quantity',
 'price',
 'region']

In [44]:
df[["order_id", "quantity", "region"]]

    order_id  quantity region
0       1001         2  North
1       1002         5  South
2       1003         3   East
3       1004         4   West
4       1005         1  North
5       1006         2  South
6       1007         6   East
7       1008         2   West
8       1009        10  North
9       1010         1  South
10      1011         1   East
11      1012         8   West
12      1013         3  North
13      1014         4  South
14      1015         2   East
15      1016         7   West
16      1017         2  North
17      1018         1  South
18      1019         5   East
19      1020         2   West

In [16]:
df.head()

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North