In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Ronal\OneDrive\Desktop\pandas-sales-analysis\data\sales.csv")

In [ ]:
df[(df["price"]> 50) & (df["region"] == "North")]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North

In [19]:
df[(df["category"] == "Electronics") | (df["category"] == "Furniture")]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West

In [11]:
df[df["category"].isin(["Electronics", "Furniture"])]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West

In [8]:
df[df["category"] != "North"]

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
6,1007,2026-01-18,John,Headphones,Accessories,6,80,East
7,1008,2026-01-20,Maria,Tablet,Electronics,2,400,West
8,1009,2026-01-22,Carlos,Mouse,Accessories,10,25,North
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
10,1011,2026-02-02,John,Laptop,Electronics,1,850,East
11,1012,2026-02-05,Maria,Keyboard,Accessories,8,45,West
12,1013,2026-02-08,Carlos,Phone,Electronics,3,600,North
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South
14,1015,2026-02-15,John,Tablet,Electronics,2,400,East
15,1016,2026-02-18,Maria,Mouse,Accessories,7,25,West
16,1017,2026-02-20,Carlos,Monitor,Electronics,2,300,North
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South
18,1019,2026-02-25,John,Keyboard,Accessories,5,45,East
19,1020,2026-02-28,Maria,Phone,Electronics,2,600,West

In [6]:
df[df["region"] == "South"]

,order_id,date,customer,product,category,quantity,price,region
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
5,1006,2026-01-15,Ana,Phone,Electronics,2,600,South
9,1010,2026-01-25,Ana,Monitor,Electronics,1,300,South
13,1014,2026-02-12,Ana,Headphones,Accessories,4,80,South
17,1018,2026-02-22,Ana,Laptop,Electronics,1,850,South

In [3]:
df[df["price"] < 30]

    order_id        date customer product     category  quantity  price region
1       1002  2026-01-06      Ana   Mouse  Accessories         5     25  South
8       1009  2026-01-22   Carlos   Mouse  Accessories        10     25  North
15      1016  2026-02-18    Maria   Mouse  Accessories         7     25   West

In [7]:
row, column = df.shape
print('row:', row)
print('column:', column)

row: 20
column: 8

In [19]:
df.dtypes

order_id    int64
date          str
customer      str
product       str
category      str
quantity    int64
price       int64
region        str
dtype: object

In [15]:
list(df.columns)

['order_id',
 'date',
 'customer',
 'product',
 'category',
 'quantity',
 'price',
 'region']

In [44]:
df[["order_id", "quantity", "region"]]

    order_id  quantity region
0       1001         2  North
1       1002         5  South
2       1003         3   East
3       1004         4   West
4       1005         1  North
5       1006         2  South
6       1007         6   East
7       1008         2   West
8       1009        10  North
9       1010         1  South
10      1011         1   East
11      1012         8   West
12      1013         3  North
13      1014         4  South
14      1015         2   East
15      1016         7   West
16      1017         2  North
17      1018         1  South
18      1019         5   East
19      1020         2   West

In [16]:
df.head()

,order_id,date,customer,product,category,quantity,price,region
0,1001,2026-01-05,Carlos,Laptop,Electronics,2,850,North
1,1002,2026-01-06,Ana,Mouse,Accessories,5,25,South
2,1003,2026-01-08,John,Monitor,Electronics,3,300,East
3,1004,2026-01-10,Maria,Keyboard,Accessories,4,45,West
4,1005,2026-01-12,Carlos,Laptop,Electronics,1,850,North